### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by gudemoning798** [segment-anything-models-java/SAMJ-IJ#16]
When I installed SAMJ using ImageJ, I encountered the following error:

error    libmamba Error opening for reading "C:\\Users\\甯呮皵star\\micromamba\\pkgs\\protobuf-4.25.3-py311hb041b4a_0\\info\\index.json": No such file or directory
error    libmamba Error when extracting package: [json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON
critical libmamba Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/win-64/aom-3.7.1-h63175ca_0.conda]
    Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds
	at io.bioimage.modelrunner.apposed.appose.Mamba.runMamba(Mamba.java:1177)
	at io.bioimage.modelrunner.apposed.appose.Mamba.runMamba(Mamba.java:1199)
	at io.bioimage.modelrunner.apposed.appose.Mamba.create(Mamba.java:655)
	at ai.nets.samj.SamEnvManager.installEfficientViTSAMPython(SamEnvManager.java:637)
	at ai.nets.samj.SamEnvManager.installEfficientViTSAMPython(SamEnvManager.java:611)
	at ai.nets.samj.SamEnvManager.installEfficientViTSAM(SamEnvManager.java:1043)
	at ai.nets.samj.gui.SAMModelPanel.lambda$createInstallationThread$7(SAMModelPanel.java:313)
	at java.lang.Thread.run(Thread.java:750)

**Comment by carlosuc3m** [comment]
HEllo @LeileiToLanyue could you please delete the folder `appose_x86_64` in the Fiji folder and reinstall the models. It seems that your Micromamba has not been installed correctly.

Also, could you check your internet conneciton too? it seems to be a little slow.

Sorry for the late reply!
Please let me know if it still fails!

Carlos
