### ISSUE TITLE
Installing SAMJ versions

### ISSUE THREAD

**Issue by pramezcua** [segment-anything-models-java/SAMJ-IJ#21]
Hello.
 Once I have installed the SAMJ plugin in FIJI, when I open it and install any of the versions that appear I have the following problems:
1. I cannot display the window where the information appears
2. It won't let me install any of the existing versions. I attach an image of what appears to me
java.lang.Exception: Unable to connect to: https://micro.mamba.pm/api/micromamba/null/latest
	at io.bioimage.modelrunner.bioimageio.download.DownloadModel.getFileSize(DownloadModel.java:600)
	at io.bioimage.modelrunner.apposed.appose.Mamba.downloadMicromamba(Mamba.java:377)
	at io.bioimage.modelrunner.apposed.appose.Mamba.installMicromamba(Mamba.java:429)
	at ai.nets.samj.install.SamEnvManager.installMambaPython(SamEnvManager.java:966)
	at ai.nets.samj.install.SamEnvManager.installEfficientViTSAM(SamEnvManager.java:1056)
	at ai.nets.samj.gui.SAMModelPanel.lambda$createInstallationThread$7(SAMModelPanel.java:313)
	at java.lang.Thread.run(Unknown Source)
Unable to connect to https://micro.mamba.pm/api/micromamba/null/latest
java.io.FileNotFoundException: https://micro.mamba.pm/api/micromamba/null/latest
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at io.bioimage.modelrunner.apposed.appose.Mamba.lambda$downloadMicromamba$0(Mamba.java:381)
	at java.lang.Thread.run(Unknown Source)
java.io.IOException: Error downloading micromamba from: https://micro.mamba.pm/api/micromamba/null/latest
	at io.bioimage.modelrunner.apposed.appose.Mamba.downloadMicromamba(Mamba.java:393)
	at io.bioimage.modelrunner.apposed.appose.Mamba.installMicromamba(Mamba.java:429)
	at ai.nets.samj.install.SamEnvManager.installMambaPython(SamEnvManager.java:966)
	at ai.nets.samj.install.SamEnvManager.installEfficientViTSAM(SamEnvManager.java:1056)
	at ai.nets.samj.gui.SAMModelPanel.lambda$createInstallationThread$7(SAMModelPanel.java:313)
	at java.lang.Thread.run(Unknown Source)
java.lang.Exception: Unable to connect to: https://micro.mamba.pm/api/micromamba/null/latest
	at io.bioimage.modelrunner.bioimageio.download.DownloadModel.getFileSize(DownloadModel.java:600)
	at io.bioimage.modelrunner.apposed.appose.Mamba.downloadMicromamba(Mamba.java:377)
	at io.bioimage.modelrunner.apposed.appose.Mamba.installMicromamba(Mamba.java:429)
	at ai.nets.samj.install.SamEnvManager.installMambaPython(SamEnvManager.java:966)
	at ai.nets.samj.install.SamEnvManager.installEfficientViTSAM(SamEnvManager.java:1056)
	at ai.nets.samj.gui.SAMModelPanel.lambda$createInstallationThread$7(SAMModelPanel.java:321)
	at java.lang.Thread.run(Unknown Source)
Unable to connect to https://micro.mamba.pm/api/micromamba/null/latest
java.io.FileNotFoundException: https://micro.mamba.pm/api/micromamba/null/latest
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at io.bioimage.modelrunner.apposed.appose.Mamba.lambda$downloadMicromamba$0(Mamba.java:381)
	at java.lang.Thread.run(Unknown Source)
java.io.IOException: Error downloading micromamba from: https://micro.mamba.pm/api/micromamba/null/latest
	at io.bioimage.modelrunner.apposed.appose.Mamba.downloadMicromamba(Mamba.java:393)
	at io.bioimage.modelrunner.apposed.appose.Mamba.installMicromamba(Mamba.java:429)
	at ai.nets.samj.install.SamEnvManager.installMambaPython(SamEnvManager.java:966)
	at ai.nets.samj.install.SamEnvManager.installEfficientViTSAM(SamEnvManager.java:1056)
	at ai.nets.samj.gui.SAMModelPanel.lambda$createInstallationThread$7(SAMModelPanel.java:321)
	at java.lang.Thread.run(Unknown Source)

**Comment by carlosuc3m** [comment]
Hello @pramezcua 
This should have been fixed a while ago! Sorry for the delay answering. Please feel free to reopen the issue if it is not working
