### ISSUE TITLE
Error Adding Update Site on M1 Mac

### ISSUE THREAD

**Issue by lauragreenstreet** [segment-anything-models-java/SAMJ-IJ#29]
Hi, I am trying to install SAMJ on an M1 Mac running Sonoma 14.5 but am getting an error when trying to add SAMJ as an update site where I get the following error after hitting 'Apply Changes' after adding SAMJ as an update site:

```
[Wed Nov 20 14:46:25 EST 2024] [INFO] [] Reading available sites from https://imagej.net/
[Wed Nov 20 14:46:37 EST 2024] [ERROR] [] null
java.io.FileNotFoundException: https://sites.imagej.net/SAMJ/plugins/DeepImageJ-3.1.0-SNAPSHOT.jar-20241119185551
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1967)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1962)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1961)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1521)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at net.imagej.updater.util.Downloader.download(Downloader.java:117)
	at net.imagej.updater.util.Downloader.start(Downloader.java:98)
	at net.imagej.updater.Installer.start(Installer.java:154)
	at net.imagej.ui.swing.updater.UpdaterFrame.install(UpdaterFrame.java:596)
	at net.imagej.ui.swing.updater.UpdaterFrame$5.run(UpdaterFrame.java:534)
Caused by: java.io.FileNotFoundException: https://sites.imagej.net/SAMJ/plugins/DeepImageJ-3.1.0-SNAPSHOT.jar-20241119185551
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3078)
	at java.net.HttpURLConnection.getHeaderFieldDate(HttpURLConnection.java:552)
	at java.net.URLConnection.getLastModified(URLConnection.java:559)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getLastModified(HttpsURLConnectionImpl.java:436)
	at net.imagej.updater.util.Downloader.download(Downloader.java:108)
	... 4 more
[Wed Nov 20 14:52:47 EST 2024] [ERROR] [] null
java.io.FileNotFoundException: https://sites.imagej.net/SAMJ/plugins/DeepImageJ-3.1.0-SNAPSHOT.jar-20241119185551
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1967)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1962)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1961)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1521)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at net.imagej.updater.util.Downloader.download(Downloader.java:117)
	at net.imagej.updater.util.Downloader.start(Downloader.java:98)
	at net.imagej.updater.Installer.start(Installer.java:154)
	at net.imagej.ui.swing.updater.UpdaterFrame.install(UpdaterFrame.java:596)
	at net.imagej.ui.swing.updater.UpdaterFrame$5.run(UpdaterFrame.java:534)
Caused by: java.io.FileNotFoundException: https://sites.imagej.net/SAMJ/plugins/DeepImageJ-3.1.0-SNAPSHOT.jar-20241119185551
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3078)
	at java.net.HttpURLConnection.getHeaderFieldDate(HttpURLConnection.java:552)
	at java.net.URLConnection.getLastModified(URLConnection.java:559)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getLastModified(HttpsURLConnectionImpl.java:436)
	at net.imagej.updater.util.Downloader.download(Downloader.java:108)
	... 4 more
[Wed Nov 20 14:55:52 EST 2024] [INFO] [] Reading available sites from https://imagej.net/
[Wed Nov 20 14:56:24 EST 2024] [ERROR] [] null
java.io.FileNotFoundException: https://sites.imagej.net/SAMJ/plugins/DeepImageJ-3.1.0-SNAPSHOT.jar-20241119185551
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1967)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1962)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1961)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1521)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at net.imagej.updater.util.Downloader.download(Downloader.java:117)
	at net.imagej.updater.util.Downloader.start(Downloader.java:98)
	at net.imagej.updater.Installer.start(Installer.java:154)
	at net.imagej.ui.swing.updater.UpdaterFrame.install(UpdaterFrame.java:596)
	at net.imagej.ui.swing.updater.UpdaterFrame$5.run(UpdaterFrame.java:534)
Caused by: java.io.FileNotFoundException: https://sites.imagej.net/SAMJ/plugins/DeepImageJ-3.1.0-SNAPSHOT.jar-20241119185551
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3078)
	at java.net.HttpURLConnection.getHeaderFieldDate(HttpURLConnection.java:552)
	at java.net.URLConnection.getLastModified(URLConnection.java:559)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getLastModified(HttpsURLConnectionImpl.java:436)
	at net.imagej.updater.util.Downloader.download(Downloader.java:108)
	... 4 more
```

I have ImageJ2 2.14.0 installed through the Fiji app in my applications folder.

Let me know if you need any additional information and thanks in advance for any advice!

**Comment by carlosuc3m** [comment]
Hello @lauragreenstreet 
It should be fixed now!!
Could you please try it?

**Comment by lauragreenstreet** [comment]
Perfect! I was able to add the update site.
